name: Build

<<<<<<< HEAD
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * *  1"
=======
'env':
  'GO_VERSION': '1.18'

'on':
  'push':
    'tags':
      - 'v*'
    'branches':
      - '*'
  'pull_request':
>>>>>>> 2193a7198ae85d7a3ba633140d74eded38096e70

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.19.0
      - name: Checkout codebase
        uses: actions/checkout@main

      - name: Build release
        run: |-
          set -e -u -x

          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo "RELEASE_VERSION=\"${RELEASE_VERSION}\"" >> $GITHUB_ENV

          make VERBOSE=1 VERSION="${RELEASE_VERSION}" release

          ls -l build/dnsproxy-*
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: ./build/dnsproxy-*.zip
          file_glob: true
